[package]
name = "shetaye_me"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = "0.8.4"
maud = { version = "0.27.0" }
mime_guess = "2.0.5"
pulldown-cmark = { version = "0.13.0", features = ["simd"] }
rust-embed="8.7.2"
time = { version = "0.3", features = ["macros"] }
tokio = { version = "1", features = ["full"] }
