baseURL = 'https://shetaye.me'
languageCode = 'en-us'
title = 'Joseph Shetaye'

pygmentsUseClasses = true
pygmentsCodefences = true

[markup.highlight]
  codeFences = true
  guessSyntax = true
  tabWidth = 4
  noClasses = false
  lineNoStart = 1
  lineNos = false
  lineNumbersInTable = true
