/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./src/**/*.rs"],
  darkMode: 'media', // Use prefers-color-scheme
  theme: {
    extend: {
      fontFamily: {
        sans: ['"Iosevka Aile"', 'system-ui', 'sans-serif'],
        serif: ['Lora', 'Georgia', '"Times New Roman"', 'serif'],
        mono: ['Iosevka', 'Consolas', 'Monaco', 'monospace'],
      },
      colors: {
        border: {
          DEFAULT: '#ddd',
          dark: '#333',
        },
        modus: {
          'bg-main': 'var(--modus-bg-main)',
          'bg-dim': 'var(--modus-bg-dim)',
          'fg-main': 'var(--modus-fg-main)',
          'fg-dim': 'var(--modus-fg-dim)',
          'fg-alt': 'var(--modus-fg-alt)',
          'bg-active': 'var(--modus-bg-active)',
          'bg-inactive': 'var(--modus-bg-inactive)',
          'border': 'var(--modus-border)',
          'red': 'var(--modus-red)',
          'red-warmer': 'var(--modus-red-warmer)',
          'red-cooler': 'var(--modus-red-cooler)',
          'red-faint': 'var(--modus-red-faint)',
          'red-intense': 'var(--modus-red-intense)',
          'green': 'var(--modus-green)',
          'green-warmer': 'var(--modus-green-warmer)',
          'green-cooler': 'var(--modus-green-cooler)',
          'green-faint': 'var(--modus-green-faint)',
          'green-intense': 'var(--modus-green-intense)',
          'yellow': 'var(--modus-yellow)',
          'yellow-warmer': 'var(--modus-yellow-warmer)',
          'yellow-cooler': 'var(--modus-yellow-cooler)',
          'yellow-faint': 'var(--modus-yellow-faint)',
          'yellow-intense': 'var(--modus-yellow-intense)',
          'blue': 'var(--modus-blue)',
          'blue-warmer': 'var(--modus-blue-warmer)',
          'blue-cooler': 'var(--modus-blue-cooler)',
          'blue-faint': 'var(--modus-blue-faint)',
          'blue-intense': 'var(--modus-blue-intense)',
          'magenta': 'var(--modus-magenta)',
          'magenta-warmer': 'var(--modus-magenta-warmer)',
          'magenta-cooler': 'var(--modus-magenta-cooler)',
          'magenta-faint': 'var(--modus-magenta-faint)',
          'magenta-intense': 'var(--modus-magenta-intense)',
          'cyan': 'var(--modus-cyan)',
          'cyan-warmer': 'var(--modus-cyan-warmer)',
          'cyan-cooler': 'var(--modus-cyan-cooler)',
          'cyan-faint': 'var(--modus-cyan-faint)',
          'cyan-intense': 'var(--modus-cyan-intense)',
          'rust': 'var(--modus-rust)',
          'gold': 'var(--modus-gold)',
          'olive': 'var(--modus-olive)',
          'slate': 'var(--modus-slate)',
          'indigo': 'var(--modus-indigo)',
          'maroon': 'var(--modus-maroon)',
          'pink': 'var(--modus-pink)',
        },
      },
    },
  },
  plugins: [],
}
